### ISSUE TITLE
terminate called after throwing an instance of 'Exception'

### ISSUE THREAD

**Issue by khkramer** [Ancurio/mkxp#169]
There's a certain conditional branch in a game I'm porting and whenever it changes the value of a certain switch ( that also happens to be the branch condition ), the game crashes with only the error message shown in the title.

Any idea's?
I've also tried recompiling mkxp with `-fexceptions` but that didn't give me any additional info.

The conditional branch in question:

![](http://i.imgur.com/Kd7BPVE.png)

I've found that if I remove the part where it sets switch 105 to OFF it doesn't crash.

**Comment by Ancurio** [comment]
Is this on Linux? If so, can you run mkxp under `gdb` and post a backtrace of where the exception is thrown? (Running `bt` in the gdb prompt after the crash).

**Comment by khkramer** [comment]
On Windows unfortunately, I'll see if I can get it running under WinGDB and post back with results.

**Comment by khkramer** [comment]
I ran it under GDB and only got the following output which is also not very useful I'm afraid..

!()[http://i.imgur.com/bdkvJ3Q.png]

**Comment by khkramer** [comment]
Actually after further testing it might also be caused by events being activated which use a tileset graphic, since both instances of the crash had this in common.

The events were dependent on a switch being active, both had a tileset graphic and both had only 1 event page.

**Comment by Ancurio** [comment]
Yeah it's definitely not caused by just setting a switch, that's ruby internal. The fact that it throws the class `Exception` means that mkxp actually detected something wrong, but the exception isn't being caught by the C++-Ruby-layer, which is really weird.

Can you test what happens if you create a bitmap from a non-existant image file? Is a normal message box with the error displayed?

**Comment by khkramer** [comment]
If I create a bitmap object with a non-existant file I just get a regular message box indeed with expected ENOENT.

**Comment by Ancurio** [comment]
Can you try the commands described [here](https://stackoverflow.com/a/26695274) to get a backtrace of when the exception is thrown with gdb?

**Comment by khkramer** [comment]
Followed those instructions and this is the backtrace it outputted just before it crashed:

```
Thread 18 hit Catchpoint 1 (exception thrown), 0x0045e3b8 in __cxa_throw ()
#0  0x0045e3b8 in __cxa_throw ()
#1  0x00493104 in Disposable::guardDisposed (this=0x19414ff0) at D:/msys2/home/k-h/mkxp/src/disposable.h:71
#2  0x004037e3 in Bitmap::height (this=0x19414ff0) at D:/msys2/home/k-h/mkxp/src/bitmap.cpp:338
#3  0x0046c1dc in SpritePrivate::recomputeBushDepth (this=0x191be9b8) at D:/msys2/home/k-h/mkxp/src/sprite.c                                                      pp:130
#4  0x0046bef9 in SpritePrivate::onSrcRectChange (this=0x191be9b8) at D:/msys2/home/k-h/mkxp/src/sprite.cpp:                                                      143
#5  0x00493b0d in sigc::bound_mem_functor0<void, SpritePrivate>::operator() (this=0x19439b4c) at D:/msys2/mi                                                      ngw32/include/sigc++-2.0/sigc++/functors/mem_fun.h:1989
#6  0x004938de in sigc::adaptor_functor<sigc::bound_mem_functor0<void, SpritePrivate> >::operator() (this=0x                                                      19439b48) at D:/msys2/mingw32/include/sigc++-2.0/sigc++/adaptors/adaptor_trait.h:256
#7  0x0047a3cd in sigc::internal::slot_call0<sigc::bound_mem_functor0<void, SpritePrivate>, void>::call_it (                                                      rep=0x19439b30) at D:/msys2/mingw32/include/sigc++-2.0/sigc++/functors/slot.h:115
#8  0x0047a6e4 in sigc::internal::signal_emit0<void, sigc::nil>::emit (impl=0x191c9980) at D:/msys2/mingw32/                                                      include/sigc++-2.0/sigc++/signal.h:786
#9  0x00493d07 in sigc::signal0<void, sigc::nil>::emit (this=0x1941790c) at D:/msys2/mingw32/include/sigc++-                                                      2.0/sigc++/signal.h:2701
#10 0x00493d1f in sigc::signal0<void, sigc::nil>::operator() (this=0x1941790c) at D:/msys2/mingw32/include/s                                                      igc++-2.0/sigc++/signal.h:2709
#11 0x00416668 in Rect::set (this=0x194178f8, x=0, y=0, w=32, h=32) at D:/msys2/home/k-h/mkxp/src/etc.cpp:31                                                      5
#12 0x0042ae69 in RectSet (argc=4, argv=0x1637d1b4, self=403915200) at D:/msys2/home/k-h/mkxp/binding-mri/et                                                      c-binding.cpp:126
#13 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#14 0x63214abf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#15 0x63215ba4 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#16 0x6320a6ed in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#17 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#18 0x63217326 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#19 0x630c3c8b in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#20 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#21 0x6320a639 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#22 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#23 0x63217326 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#24 0x630c3c8b in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#25 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#26 0x6320a639 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#27 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#28 0x632162b6 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#29 0x631068ff in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#30 0x63202471 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#31 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#32 0x63214abf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#33 0x63215ba4 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#34 0x6320a639 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#35 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#36 0x632162b6 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#37 0x631068ff in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#38 0x63202471 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#39 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#40 0x63214abf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#41 0x63215ba4 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#42 0x6320a639 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#43 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#44 0x63107e2c in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#45 0x631095d5 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#46 0x631098c8 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#47 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#48 0x6320a6ed in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#49 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#50 0x63217326 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#51 0x630c3c8b in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#52 0x63204d6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#53 0x63214abf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#54 0x63215ba4 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#55 0x6320a639 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#56 0x6320e759 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#57 0x6320f6bf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#58 0x6320fb6f in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#59 0x6320fe5a in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#60 0x63211656 in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#61 0x00427df0 in evalHelper (arg=0x1506fd3c) at D:/msys2/home/k-h/mkxp/binding-mri/binding-mri.cpp:330
#62 0x63106bcf in ?? () from D:\Pokemon Infernal Red\msvcrt-ruby230.dll
#63 0x00427e22 in evalString (string=380106144, filename=380106216, state=0x0) at D:/msys2/home/k-h/mkxp/bin                                                      ding-mri/binding-mri.cpp:336
#64 0x00427f42 in runCustomScript (filename=...) at D:/msys2/home/k-h/mkxp/binding-mri/binding-mri.cpp:350
#65 0x00428eb2 in mriBindingExecute () at D:/msys2/home/k-h/mkxp/binding-mri/binding-mri.cpp:593
#66 0x00401a78 in rgssThreadFun (userdata=0x387f668) at D:/msys2/home/k-h/mkxp/src/main.cpp:139
#67 0x6c9af429 in ?? () from D:\Pokemon Infernal Red\SDL2.dll
#68 0x6c9fc45e in ?? () from D:\Pokemon Infernal Red\SDL2.dll
#69 0x77bc6781 in msvcrt!_beginthreadex () from C:\WINDOWS\System32\msvcrt.dll
#70 0x77bc6841 in msvcrt!_endthreadex () from C:\WINDOWS\System32\msvcrt.dll
#71 0x763586d4 in KERNEL32!BaseThreadInitThunk () from C:\WINDOWS\System32\kernel32.dll
#72 0x77d35017 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#73 0x77d34fe7 in ntdll!RtlGetAppContainerNamedObjectPath () from C:\WINDOWS\SYSTEM32\ntdll.dll
#74 0x00000000 in ?? ()
terminate called after throwing an instance of 'Exception'
```

**Comment by Ancurio** [comment]
Try this patch: https://pastebin.com/raw/TxWwszmZ

**Comment by khkramer** [comment]
Applied the patch, event now works as expected and the game no longer crashes.

Thanks!
